---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: timescaledb
spec:
  encryptedData:
    .dockerconfigjson: AgBWiPcmzP8VT2cbsN5FqAZB39OgsjTPl7SIHBaqPmjj8+NT+PnERGeeReph2SKSOcBz2YK/Q+WUwDgUb7UB1/qUnmHU1E8OvM1do/I9OitcVFwHvjavgCfFZLgzB9kLhVviF8Mj66IVdf8fz3eXap2UYMsgKFvhbMAkJLb1AyGjFFOwiSPn6mqggwAd9CXyYTpbRUN9e4E/mU2hZpb7nnBQpoEq28VgiejOffFKUTypeXgUSEnzU8RghDTPidWxho5qmFRyBp4z78O4A9yJEC59uxHU2y9ENZ1sL8aNJYEmwLplDvZnbEC/UCK7E+FF+74vKMr6eDnKoPyEUciKwhzorJlFUPW7h3NQl64ySGom6FlX8NKJETZeXmS3NN0WOaHgLjo+Hv4yoJGb6fxssL2x+vbJmDflTYf189i/+8tp3OflBkRvFOWJZits6JUb0gl06yw90Z4xdZmzMFEchG8DwvMEnMKmFwvdD8C8eQOsVtmMG7c9FunWjZALbHglJdsHiaIFUj7fow8A/3K2angxtG2HvCEHTosCZY1dMAuduFHE4tE7RVMrHajF2t9PAQsbxacn1mrCSvnMea0tdkk0MvIKkfRWUIHRbN7k4HUlD6yKGTFpPsCvTxelo5lvtyFJ3cNEy4Vmy9k05kBToFsKNub0r/8WJEvSW2+tEy8U9Nq1UdnSV14HUvwT5sC/9BDS2AXxaSyOLZ1jf5S3apa5lOZv6moNPkhnpoJioh3poLwVoCKjP4RLZ7RMcoRUn74IeN9ai9UuoKSJkmGqzIo0gNtOb2JRbJy/vfoGzM6pVwIFY3MWVEz8uGKtrtFDfDX/lw58yffdSjoh1J7QKRH1UMWw0xuWzA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: timescaledb
    type: kubernetes.io/dockerconfigjson
