---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: harbor-registry-secret
  namespace: timescaledb
spec:
  encryptedData:
    .dockerconfigjson: AgBWLJQWK2xxAbZhUy7lUmI230ORSCF7V3KJHwLZA9SEUArS5VVNWSsAdTkzoH5GEGreXhc9I1AcYkdAdTKfCqOtEwcukdRIt/FVb/YshmJNbpindvaernYLIkc9xTvro41nm0shv6K5vniYOPWL32MZzt1lEQUAO2wQYu4wRW8SdGv4KRHW+F6WgvdYLlBI2KDcphINsV1cY9vU/gz2o5Tr3BiXl+urAivTr6XST+VTh/nt1McxP3AEuMenQaUvrPrYGZrrQ17lYPaPe2GVQ6iUFc1eL5g4R/8DXW+/AmyjBVAqWTX7bwZiBE6Z2eMJFW01CzRJlbrbP0aiUEX8C49XH9UkgoW3Jrw/DV+Ya9blpEqNLTMr/ZO1KkjJt5WOBeSdZhN8jD/rm+M1icVQJpp1ECS7jp22fEmo3f77A5kNS/HtME+zg8zdCYNQ47rU0sm2pVpj3EJiA8d8Ep3NSr1+CiyDNn0d8daT2l0g1iz+10SHIST0oqhr/tDsdyMv0hyDqT50n20P3vdf8lqgQeg1MwJis/cKtYMbEpw5lBnw5oh0vQSRnGmVvw/WE8kDMUDbKrZBdzvF2ZKrO/6lUplLNzo0hnrwDH+XgyQggZlmamtJbAdTDI6yli9HCCJQbzkHAA4NBnJrIp2FfKCRmX2eSi7DV2Bq0SaTLxkTLUoB84JGvFmtlyKgnzsnA1NdA++VgE8i50+rzCcavVjW0eq+P+JvbhsErREDkLZ4fc79iNoe8SvvDPNSnvZINWoLUfqnMoxREpBPkQBjsTir+MnmV5jdkASlD5GnRGuJCkq8FziVxjC2GJZUSs/zfky94OwtV8Q3Qz5cs6aJsGSTqa8=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: harbor-registry-secret
      namespace: timescaledb
    type: kubernetes.io/dockerconfigjson
