# timescaledb-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: timescaledb
  namespace: timescaledb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb:latest-pg14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: mydatabase
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
          resources:
            requests:
              memory: "1Gi" # Minimum memory required
              cpu: "500m" # Minimum CPU required
            limits:
              memory: "2Gi" # Maximum memory the container can use
              cpu: "1" # Maximum CPU the container can use
          volumeMounts:
            - name: timescaledb-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: timescaledb-storage
          persistentVolumeClaim:
            claimName: timescaledb-pvc
